name: Dependency Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Nancy
      run: |
        curl -fsSL https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.15/nancy_1.0.15_linux_amd64.deb -o nancy.deb
        sudo dpkg -i nancy.deb
        rm -rf vendor
        go list -json -m all | nancy sleuth --loud > dependency-report.txt
        text2html --paras --blockcode dependency-report.txt

    - name: Backup HTML Report
      if: "${{ always() }}"
      uses: actions/upload-artifact@v2
      with:
        name: dependency-report
        path: ./dependency-report.txt
