name: Dependency Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  dependency-check:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Create Go.list
      run: |
        rm -rf vendor
        go list -json -m all > go.list

    - name: Generate Report
      if: "${{ always() }}"
      uses: sonatype-nexus-community/nancy-github-action@main
      with: 
        nancyCommand: sleuth --loud\" > dependency-report.txt
        
    - name: Gen Txt
      if: "${{ always() }}"
      run: |
        cat $GITHUB_ENV >> result.txt
        
    - name: Backup HTML Report
      if: "${{ always() }}"
      uses: actions/upload-artifact@v2
      with:
        name: dependency-report
        path: ./dependency-report.txt

